
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('patients').del()
    .then(function () {
      // Inserts seed entries
      return knex('patients').insert([
        {
          first_name: 'John',
          last_name: 'Smithe',
          doctor: 'Dr. Abraham Kennedy',
          emergency_contact_name: 'Kelly Smithe',
          emergency_contact_number: '1234567890',
          allergies: 'People who code on master',
          previous_injuries: 'Broken hip',
          recent_illness: 'Pneumonia',
          notes: 'Enjoys long walks down the hall',
          bed_id: 1,
          nurse_id: 1
        },
        {
          first_name:  'Phil',
          last_name: 'Doe',
          doctor: 'Dr. Abraham Kennedy',
          emergency_contact_name: 'Ken Doe',
          emergency_contact_number: '1234567890',
          allergies: 'Shellfish',
          previous_injuries: 'none',
          recent_illness: 'Strep throat',
          notes: 'Thinks Annie is his long lost love',
          bed_id: 2,
          nurse_id: 3
        },
        {
          first_name: 'Beatrice',
          last_name: 'Ranger',
          doctor: 'Dr. Justin Harper',
          emergency_contact_name: 'Michael Ranger',
          emergency_contact_number: '1234567890',
          allergies: 'Peanuts',
          previous_injuries: 'Brain injury',
          recent_illness: 'none',
          notes: 'Thinks it is 1970',
          bed_id: 6,
          nurse_id: 5
        },
        {
          first_name: 'Gertrude',
          last_name: 'Lim',
          doctor: 'Dr. Justin Harper',
          emergency_contact_name: 'Peter Lim',
          emergency_contact_number: '1234567890',
          allergies: 'Poor version control',
          previous_injuries: 'none',
          recent_illness: 'none',
          notes: 'Thinks Parker is her long lost love',
          bed_id: 4,
          nurse_id: 6
        },
        {
          first_name: 'Lana',
          last_name: 'Lee',
          doctor: 'Dr. Justin Harper',
          emergency_contact_name: 'Harold Lee',
          emergency_contact_number: '1234567890',
          allergies: 'Gluten',
          previous_injuries: 'none',
          recent_illness: 'Diabeties',
          notes: 'Diabetic',
          bed_id: 5,
          nurse_id: 7
        },
        {
          first_name: 'Sterling',
          last_name: 'Chuck',
          doctor: 'Dr. Abraham Kennedy',
          emergency_contact_name: 'Chris Chuck',
          emergency_contact_number: '1234567890',
          allergies: 'none',
          previous_injuries: 'none',
          recent_illness: 'Lung Cancer',
          notes: 'Enjoys talking about his grandchildren',
          bed_id: 21,
          nurse_id: 1
        },
        {
          first_name: 'Bob',
          last_name: 'Smith',
          doctor: 'Dr. Barack Bush',
          emergency_contact_name: 'Carol Smith',
          emergency_contact_number: '1234567890',
          allergies: 'none',
          previous_injuries: 'none',
          recent_illness: 'Dementia',
          notes: 'Goes in and out day to day',
          bed_id: 8,
          nurse_id: 3
        },
        {
          first_name: 'Pepe',
          last_name: 'Silvia',
          doctor: 'Dr. Barack Bush',
          emergency_contact_name: 'Carol Silvia',
          emergency_contact_number: '1234567890',
          allergies: 'none',
          previous_injuries: 'none',
          recent_illness: 'none',
          notes: 'Goes missing at times',
          bed_id: 14,
          nurse_id: 5
        },
        {
          first_name: 'Jacob',
          last_name: 'David',
          doctor: 'Dr. Abraham Kennedy',
          emergency_contact_name: 'Song David',
          emergency_contact_number: '1234567890',
          allergies: 'Peanuts',
          previous_injuries: 'Broken',
          recent_illness: 'none',
          notes: 'Many sickness',
          bed_id: 23,
          nurse_id: 6
        },
        {
          first_name: 'Moe',
          last_name: 'Sinatra',
          doctor: 'Dr. Justin Harper',
          emergency_contact_name: 'Francis Sinatra',
          emergency_contact_number: '1234567890',
          allergies: 'Banana',
          previous_injuries: 'none',
          recent_illness: 'Conjunctivitis',
          notes: 'none',
          bed_id: 7,
          nurse_id: 7
        },
        {
          first_name: 'Frank',
          last_name: 'Pitt',
          doctor: 'Dr. Justin Harper',
          emergency_contact_name: 'Tom Pitt',
          emergency_contact_number: '1234567890',
          allergies: 'Coconut',
          previous_injuries: 'none',
          recent_illness: 'Pneumonia',
          notes: 'none',
          bed_id: 20,
          nurse_id: 1
        },
        {
          first_name: 'Andrew',
          last_name: 'Franklin',
          doctor: 'Dr. Abraham Kennedy',
          emergency_contact_name: 'Vlad Franklin',
          emergency_contact_number: '1234567890',
          allergies: 'none',
          previous_injuries: 'Broken Femur',
          recent_illness: 'none',
          notes: 'Requires silence to sleep',
          bed_id: 13,
          nurse_id: 3
        },
        {
          first_name: 'Myles',
          last_name: 'Johnson',
          doctor: 'Dr. Abraham Kennedy',
          emergency_contact_name: 'George Johnson',
          emergency_contact_number: '1234567890',
          allergies: 'Off-by-one errors',
          previous_injuries: 'Fracture clavicle',
          recent_illness: 'none',
          notes: 'Randomly bursts into song',
          bed_id: 9,
          nurse_id: 5
        },
        {
          first_name: 'Steven',
          last_name: 'Jimmy',
          doctor: 'Dr. Barack Bush',
          emergency_contact_name: 'Henry Jimmy',
          emergency_contact_number: '1234567890',
          allergies: 'Poor indentation',
          previous_injuries: 'none',
          recent_illness: 'none',
          notes: 'Has two first names',
          bed_id: 12,
          nurse_id: 6
        },
        {
          first_name: 'Wesley',
          last_name: 'Quebert',
          doctor: 'Dr. Barack Bush',
          emergency_contact_name: 'Simon Quebert',
          emergency_contact_number: '1234567890',
          allergies: 'Apples',
          previous_injuries: 'none',
          recent_illness: 'none',
          notes: 'Very aggressive',
          bed_id: 18,
          nurse_id: 7
        },
        {
          first_name: 'Henry',
          last_name: 'Ford',
          doctor: 'Dr. Abraham Kennedy',
          emergency_contact_name: 'Harrison Ford',
          emergency_contact_number: '1234567890',
          allergies: 'Pineapple',
          previous_injuries: 'Skin cancer',
          recent_illness: 'none',
          notes: 'Thinks he is related to a movie star',
          bed_id: 17,
          nurse_id: 1
        },
        {
          first_name: 'George',
          last_name: 'Chan',
          doctor: 'Dr. Barack Bush',
          emergency_contact_name: 'Claire Forest',
          emergency_contact_number: '1234567890',
          allergies: 'Fabric softener ',
          previous_injuries: 'none',
          recent_illness: 'none',
          notes: 'Enjoys talking about the stock market',
          bed_id: 15,
          nurse_id: 3
        },
        {
          first_name: 'Tom',
          last_name: 'Tracy',
          doctor: 'Dr. Barack Bush',
          emergency_contact_name: 'Morgan Tracy',
          emergency_contact_number: '1234567890',
          allergies: 'Fruit',
          previous_injuries: 'Broken hip',
          recent_illness: 'none',
          notes: 'Uncomfortable peeing, while somebody else is in the room',
          bed_id: 16,
          nurse_id: 5
        },
        {
          first_name: 'Theodore',
          last_name: 'Killroy',
          doctor: 'Dr. Justin Harper',
          emergency_contact_name: 'Alan Killroy',
          emergency_contact_number: '1234567890',
          allergies: 'none',
          previous_injuries: 'none',
          recent_illness: 'Colon cancer',
          notes: 'Very shy',
          bed_id: 10,
          nurse_id: 6
        },
        {
          first_name: 'Amanda',
          last_name: 'Roy',
          doctor: 'Dr. Justin Harper',
          emergency_contact_name: 'Patrick Roy',
          emergency_contact_number: '1234567890',
          allergies: 'Callback hell',
          previous_injuries: 'Broken jaw',
          recent_illness: 'none',
          notes: 'Very strong opinions on using VIM',
          bed_id: 11,
          nurse_id: 7
        }
      ]);
    });
};
